sudo: required
services:
  - docker

before_install:
  - docker build -t nandinikodipunzula/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nandinikodipunzula/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-975049916169"
  bucket_path: "frontend"
  on:
    branch: main
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
